parameters:
#    mo_movie.example.class: MO\Bundle\MovieBundle\Example

services:
#    mo_movie.example:
#        class: %mo_movie.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    mo_movie.manager.movie_manager:
        class: MO\Bundle\MovieBundle\Manager\MovieManager
        arguments: [@mo_movie.provider.pathe]


    mo_movie.provider.pathe:
        class: MO\Bundle\MovieBundle\MovieDataProviders\PatheProvider
        arguments: [@mo_movie.pool.cinema, @mo_movie.cache.movie_cache]

    mo_movie.pool.cinema:
        class: MO\Bundle\MovieBundle\MovieDataProviders\CinemaPool

    mo_movie.manager.movie_matcher:
        class: MO\Bundle\MovieBundle\Manager\MovieMatcherManager
        arguments: [@mo_movie.manager.movie_manager, @mo_movie.cache.movie_cache]

    #Twig extensions
    mo_movie.twig.locale_extension:
        class: MO\Bundle\MovieBundle\Twig\LocaleTwigExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }



    #Movie cache
    mo_movie.cache.movie_cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ["%kernel.cache_dir%/mo/movie_cache"]