parameters:
#    mo_movie.example.class: MO\Bundle\MovieBundle\Example
    mo_movie.cache.movie_cache_path: "/mo/movie_cache"

services:
#    mo_movie.example:
#        class: %mo_movie.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    mo_movie.manager.movie_manager:
        class: MO\Bundle\MovieBundle\Manager\MovieManager
        arguments: [@mo_movie.provider.pathe]


    mo_movie.provider.pathe:
        class: MO\Bundle\MovieBundle\MovieDataProviders\PatheProvider
        arguments: [@mo_movie.pool.cinema, @mo_movie.cache.movie_cache, @service_container]

    mo_movie.pool.cinema:
        class: MO\Bundle\MovieBundle\MovieDataProviders\CinemaPool

    mo_movie.manager.movie_matcher:
        class: MO\Bundle\MovieBundle\Manager\MovieMatcherManager
        arguments: [@mo_movie.manager.movie_manager, @mo_movie.cache.movie_cache, "%app.cities.default%", @?debug.stopwatch]

    #Twig extensions
    mo_movie.twig.locale_extension:
        class: MO\Bundle\MovieBundle\Twig\LocaleTwigExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    #language listener
    mo_movie.language.kernel_request_listener:
        class: MO\Bundle\MovieBundle\EventListener\LanguageListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setLocale }

    #City listener
    mo_movie.city.kernel_request_listener:
        class: MO\Bundle\MovieBundle\EventListener\CityListener
        arguments: [@router]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setCity }


    #Forms
    mo_movie.form.type.search_form:
        class: MO\Bundle\MovieBundle\Form\SearchFormType
        scope: request
        arguments: [@mo_movie.manager.movie_manager, @router, @request]
        tags:
            - { name: form.type, alias: search_form }


    #Movie cache
    mo_movie.cache.movie_cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ["%kernel.cache_dir%%mo_movie.cache.movie_cache_path%"]


    #cache
    mo_movie.cache.warmer:
        class: MO\Bundle\MovieBundle\Cache\MovieWarmer
        arguments: [@service_container, "%mo_movie.cache.movie_cache_path%"]
        tags:
          - { name: kernel.cache_warmer, priority: 0 }